# SwiftLint configuration for Nimoy

included:
  - Nimoy
  - NimoyTests

excluded:
  - Nimoy.xcodeproj
  - .build
  - DerivedData

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length  # We'll use swiftformat for this
  - identifier_name  # Allow short names like x, y, i
  - multiple_closures_with_trailing_closure  # SwiftUI uses this pattern
  - implicit_optional_initialization  # Allow explicit nil
  - control_statement  # Minor style preference
  - vertical_whitespace  # SwiftFormat handles this

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  # - force_unwrapping  # Enable later
  # - implicitly_unwrapped_optional  # Enable later
  - last_where
  - legacy_random
  # - missing_docs  # Enable later - requires documentation for public declarations
  - modifier_order
  # - multiline_arguments  # Can conflict with swiftformat
  # - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
# missing_docs:  # Enable when ready to require documentation
#   warning: public
#   excludes_extensions: true
#   excludes_inherited_types: true

force_cast:
  severity: warning

force_try:
  severity: warning

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 800
  error: 1500
  ignore_comment_only_lines: true

nesting:
  type_level: 4
  function_level: 4

cyclomatic_complexity:
  warning: 30
  error: 60

reporter: xcode
